import type { Metadata } from "next";
import "@/styles/globals.css";
import { Footer, Navbar } from "@/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="bg-gray-100 min-h-screen">
          {/* Navbar */}
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
